package files

import (
	b64 "encoding/base64"
)

const configText = "cGFja2FnZSBjb25maWcKCmltcG9ydCAoCgkiZ2l0aHViLmNvbS9zcGYxMy92aXBlciIKKQoKdHlwZSBDb25mIHN0cnVjdCB7Cn0KCmZ1bmMgTG9hZENvbmZpZyhwYXRoIHN0cmluZykgKCpDb25mLCBlcnJvcikgewoJdmFyIGNmZyAqQ29uZgoJdmlwZXIuU2V0Q29uZmlnTmFtZSgiY29uZmlnIikKCXZpcGVyLlNldENvbmZpZ1R5cGUoImVudiIpCgl2aXBlci5BZGRDb25maWdQYXRoKHBhdGgpCgl2aXBlci5TZXRDb25maWdGaWxlKCIuZW52IikKCXZpcGVyLkF1dG9tYXRpY0VudigpCgoJZXJyIDo9IHZpcGVyLlJlYWRJbkNvbmZpZygpCglpZiBlcnIgIT0gbmlsIHsKCQlyZXR1cm4gbmlsLCBlcnIKCX0KCgllcnIgPSB2aXBlci5Vbm1hcnNoYWwoJmNmZykKCglpZiBlcnIgIT0gbmlsIHsKCQlyZXR1cm4gbmlsLCBlcnIKCX0KCglyZXR1cm4gY2ZnLCBuaWwKCn0K"

const dockerFile = "RlJPTSBnb2xhbmc6MS4yMiBhcyBidWlsZGVyCldPUktESVIgL2FwcApDT1BZIC4gLgoKUlVOIGdvIG1vZCBkb3dubG9hZApSVU4gZ28gYnVpbGQgLW8gbWFpbiAuCgoKRlJPTSBzY3JhdGNoCldPUktESVIgL2FwcApDT1BZIC0tZnJvbT1idWlsZGVyIC9hcHAvbWFpbiAvYXBwLwpDT1BZIC0tZnJvbT1idWlsZGVyIC9hcHAvLmVudiAvYXBwLwoKQ01EIFsiLi9tYWluIl0="

func GetConfigText() []byte {
	text, _ := b64.StdEncoding.DecodeString(configText)
	return text
}

func GetDockerFile() []byte {
	text, _ := b64.StdEncoding.DecodeString(dockerFile)
	return text
}
